profile-name : local

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.0.117:3306/multi?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: multi
    password: multi123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

# feign
feign:
  url:
    prefix: http://localhost:8080/target_server # DemoFeign?? ??? url prefix
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000
        logger-level: none
      demo-client: # DemoFeignClient?? ??? Client?? ?
        connect-timeout: 1000
        read-timeout: 10000
        logger-level: headers # ??? ??? ?? FeignCustomLogger -> Logger.Level logLevel ??? ??